pgsql:
  image: mikeneck/pg-sql-for-artifactory
artifactory:
  image: mikeneck/artifactory-with-pg-sql
  ports:
    - "8864:8081"
  links:
    - pgsql
  volumes:
    - ./home/backup:/home/artifactory/artifactory/backup
    - ./home/data:/home/artifactory/artifactory/data
    - ./home/logs:/home/artifactory/artifactory/logs
